New cleanup feature to support CEPH storage backend
the-cloudkeeper-project/cloudkeeper-os pull request #14
Opened 2017-12-14 10:37 UTC by Pansanel

2017-12-15 09:10 UTC, Mamut3D commented
Thanks for the PR, I will test it

2018-01-16 18:24 UTC, Pansanel commented
Could you test it?

2018-01-16 19:14 UTC, Mamut3D requested changes

2018-01-16 19:14 UTC, Mamut3D commented on cloudkeeper_os/imagemanager.py
> +        properties[IMAGE_STATUS_TAG] = 'ACTIVE'
I have tried it, however for some reason `APPLIANCE_STATUS` does not seem to be propagating to openstack as an attribute. 
Can you verify that it correctly propagates to openstack?

2018-01-16 19:14 UTC, Mamut3D commented on cloudkeeper_os/imagemanager.py
> +        properties[IMAGE_STATUS_TAG] = 'EOL'
Same as the above,  can you verify propagation?

2018-01-17 07:50 UTC, Mamut3D commented on cloudkeeper_os/imagemanager.py
> +        properties[IMAGE_STATUS_TAG] = 'EOL'
Sorry for the late response, I have tested the code during December, however I have left the review in unsubmitted state by mistake.

2018-02-05 11:52 UTC, Pansanel commented on cloudkeeper_os/imagemanager.py
> +        properties[IMAGE_STATUS_TAG] = 'EOL'
I have test on my infra, I have the 'APPLIANCE_STATUS' tag set to 'ACTIVE, as requested. Can you run cloudkeeper-os in verbose mode on your side to see what happens?
You can also perform a quick test with this SQL query:
`MariaDB [glance]> select distinct(name) from image_properties;`

2018-02-09 09:17 UTC, Pansanel commented
I have test on my infra, I have the 'APPLIANCE_STATUS' tag set to 'ACTIVE, as requested. Can you run cloudkeeper-os in verbose mode on your side to see what happens?
You can also perform a quick test with this SQL query to see if the tag exists:
```MariaDB [glance]> select distinct(name) from image_properties;```

2018-02-15 17:24 UTC, Mamut3D commented
I am sorry, I am currently unable to test it further. If it works for you, just merge the request.

2018-02-15 20:22 UTC, merged